-- Enable the UUID extension
create extension if not exists "uuid-ossp";

-- Reset (Drop existing tables if they exist)
drop table if exists public.habit_logs;
drop table if exists public.habits;
drop table if exists public.user_characters;
drop table if exists public.character_evolutions;
drop table if exists public.characters;
drop table if exists public.flyers; -- Old table
-- Keeping public.users as it syncs with auth.users

-- 1. Users table (Public profile) - Mirroring Supabase Auth
create table if not exists public.users (
  id bigint generated by default as identity primary key,
  uuid uuid references auth.users not null unique,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.users enable row level security;

-- Policies for users
create policy "Public profiles are viewable by everyone."
  on public.users for select
  using ( true );

create policy "Users can insert their own profile."
  on public.users for insert
  with check ( auth.uid() = uuid );

create policy "Users can update own profile."
  on public.users for update
  using ( auth.uid() = uuid );

-- 2. Characters Master Table
create table public.characters (
  id serial primary key,
  name varchar(50) not null,
  description text,
  base_image_url varchar(255), -- Or Emoji
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.characters enable row level security;
create policy "Characters are viewable by everyone." on public.characters for select using (true);

-- 3. Character Evolutions
create table public.character_evolutions (
  id serial primary key,
  character_id int references public.characters(id) on delete cascade not null,
  level_required int not null,
  image_url varchar(255) not null,
  evolution_name varchar(50)
);

alter table public.character_evolutions enable row level security;
create policy "Evolutions are viewable by everyone." on public.character_evolutions for select using (true);

-- 4. User Characters (Selected character and progress)
create table public.user_characters (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id) on delete cascade not null unique,
  character_id int references public.characters(id) not null,
  current_xp int default 0 not null,
  current_level int default 1 not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.user_characters enable row level security;
create policy "Users can view own character progress." on public.user_characters for select using (auth.uid() = user_id);
create policy "Users can choose their character." on public.user_characters for insert with check (auth.uid() = user_id);
create policy "Users can update own character progress." on public.user_characters for update using (auth.uid() = user_id);

-- 5. Habits Table
create type habit_difficulty as enum ('easy', 'normal', 'hard');

create table public.habits (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  title varchar(100) not null,
  description text,
  difficulty habit_difficulty default 'normal' not null,
  mon boolean default false,
  tue boolean default false,
  wed boolean default false,
  thu boolean default false,
  fri boolean default false,
  sat boolean default false,
  sun boolean default false,
  is_active boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table public.habits enable row level security;
create policy "Users can manage own habits." on public.habits for all using (auth.uid() = user_id);

-- 6. Habit Logs (History of completions)
create table public.habit_logs (
  id uuid default uuid_generate_v4() primary key,
  habit_id uuid references public.habits(id) on delete cascade not null,
  user_id uuid references auth.users(id) on delete cascade not null,
  completed_date date default current_date not null,
  xp_earned int not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(habit_id, completed_date) -- Prevent multiple clears for same habit on same day
);

alter table public.habit_logs enable row level security;
create policy "Users can view/insert own logs." on public.habit_logs for all using (auth.uid() = user_id);

-- 7. Initial Character Data
insert into public.characters (name, description, base_image_url) values
('푸딩이', '온순하고 느긋한 성격의 젤리 캐릭터입니다.', '🐱'),
('코코', '활발하고 에너지 넘치는 강아지 캐릭터입니다.', '🐶'),
('모찌', '수줍음이 많지만 다정한 토끼 캐릭터입니다.', '🐰');

-- Initial Evolutions (Example)
insert into public.character_evolutions (character_id, level_required, image_url, evolution_name) values
(1, 1, '🐱', '아기 푸딩이'),
(1, 5, '🐈', '청년 푸딩이'),
(1, 10, '🦁', '황제 푸딩이'),
(2, 1, '🐶', '아기 코코'),
(2, 5, '🐕', '청년 코코'),
(2, 10, '🐺', '대장 코코'),
(3, 1, '🐰', '아기 모찌'),
(3, 5, '🐇', '청년 모찌'),
(3, 10, '🦄', '전설의 모찌');

-- 8. Functions & Triggers for User Sync (Keeping these from old schema)
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.users (uuid, email, full_name, avatar_url)
  values (
    new.id,
    new.email,
    coalesce(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      ''
    ),
    new.raw_user_meta_data->>'avatar_url'
  )
  on conflict (uuid) do update
  set
    email = excluded.email,
    full_name = excluded.full_name,
    avatar_url = excluded.avatar_url,
    updated_at = now();
  return new;
end;
$$ language plpgsql security definer;

create or replace function public.handle_user_update()
returns trigger as $$
begin
  update public.users
  set
    email = new.email,
    full_name = coalesce(
      new.raw_user_meta_data->>'full_name',
      new.raw_user_meta_data->>'name',
      full_name
    ),
    avatar_url = coalesce(
      new.raw_user_meta_data->>'avatar_url',
      avatar_url
    ),
    updated_at = now()
  where uuid = new.id;
  return new;
end;
$$ language plpgsql security definer;

create or replace function public.handle_user_delete()
returns trigger as $$
begin
  delete from public.users where uuid = old.id;
  return old;
end;
$$ language plpgsql security definer;

-- Triggers
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

drop trigger if exists on_auth_user_updated on auth.users;
create trigger on_auth_user_updated
  after update on auth.users
  for each row
  when (
    old.email is distinct from new.email OR
    old.raw_user_meta_data is distinct from new.raw_user_meta_data
  )
  execute procedure public.handle_user_update();

drop trigger if exists on_auth_user_deleted on auth.users;
create trigger on_auth_user_deleted
  after delete on auth.users
  for each row execute procedure public.handle_user_delete();
