-- Enable the UUID extension
create extension if not exists "uuid-ossp";

-- Reset (Drop existing tables if they exist)
drop table if exists public.flyers;
drop table if exists public.users;


-- Users table (Public profile)
-- This table mirrors the Supabase Auth users table
create table public.users (
  id bigint generated by default as identity primary key,
  uuid uuid references auth.users not null unique,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on users
alter table public.users enable row level security;

-- Policies for users
create policy "Public profiles are viewable by everyone."
  on public.users for select
  using ( true );

create policy "Users can insert their own profile."
  on public.users for insert
  with check ( auth.uid() = uuid );

create policy "Users can update own profile."
  on public.users for update
  using ( auth.uid() = uuid );

-- Flyers table
create table public.flyers (
  id bigint generated by default as identity primary key,
  uuid uuid default uuid_generate_v4() not null unique,
  title text not null,
  description text,
  image_url text,
  user_id uuid references public.users(uuid) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on flyers
alter table public.flyers enable row level security;

-- Policies for flyers
create policy "Flyers are viewable by everyone."
  on public.flyers for select
  using ( true );

create policy "Users can insert their own flyers."
  on public.flyers for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own flyers."
  on public.flyers for update
  using ( auth.uid() = user_id );

create policy "Users can delete own flyers."
  on public.flyers for delete
  using ( auth.uid() = user_id );
