-- Enable the UUID extension
create extension if not exists "uuid-ossp";

-- Reset (Drop existing tables if they exist)
drop table if exists public.flyers;
drop table if exists public.users;


-- Users table (Public profile)
-- This table mirrors the Supabase Auth users table
create table public.users (
  id bigint generated by default as identity primary key,
  uuid uuid references auth.users not null unique,
  email text,
  full_name text,
  avatar_url text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on users
alter table public.users enable row level security;

-- Policies for users
create policy "Public profiles are viewable by everyone."
  on public.users for select
  using ( true );

create policy "Users can insert their own profile."
  on public.users for insert
  with check ( auth.uid() = uuid );

create policy "Users can update own profile."
  on public.users for update
  using ( auth.uid() = uuid );

-- Flyers table
create table public.flyers (
  id bigint generated by default as identity primary key,
  uuid uuid default uuid_generate_v4() not null unique,
  title text not null,
  description text,
  image_url text,
  user_id uuid references public.users(uuid) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS on flyers
alter table public.flyers enable row level security;

-- Policies for flyers
create policy "Flyers are viewable by everyone."
  on public.flyers for select
  using ( true );

create policy "Users can insert their own flyers."
  on public.flyers for insert
  with check ( auth.uid() = user_id );

create policy "Users can update own flyers."
  on public.flyers for update
  using ( auth.uid() = user_id );

create policy "Users can delete own flyers."
  on public.flyers for delete
  using ( auth.uid() = user_id );

-- Add html_content to flyers table
alter table public.flyers
  add column if not exists html_content text;

-- Storage Bucket Setup (Update public status if exists)
insert into storage.buckets (id, name, public)
values ('flyers', 'flyers', true)
on conflict (id) do update set public = true;

-- Storage Policies
create policy "Authenticated users can upload flyer images"
on storage.objects for insert
to authenticated
with check ( bucket_id = 'flyers' );

create policy "Anyone can view flyer images"
on storage.objects for select
using ( bucket_id = 'flyers' );

create policy "Users can delete own flyer images"
on storage.objects for delete
to authenticated
using (
  bucket_id = 'flyers' AND
  owner = auth.uid()
);
